# FILEPATH: /.github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: go to the directory
      run: cd client

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
